import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Application root layout that applies global fonts and provides theme context.
 *
 * Renders the top-level HTML structure (<html> and <body>) with configured font CSS variables,
 * antialiasing, and a ThemeProvider that supplies theme state to the app.
 *
 * @param children - The page content to render inside the ThemeProvider.
 * @returns A JSX element representing the application's root HTML/body wrapper with theme and fonts applied.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem storageKey="yearbook-theme">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}